enviroment:
  QTDIR: C:\Qt\5.9\mingw53_32
  PATH: %PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - git submodule update --init --recursive
  - qmake CONFIG+=nopkg KShare.pro
  - curl -kLO https://ffmpeg.zeranoe.com/builds/win64/dev/ffmpeg-3.3.2-win64-dev.zip
  - 7z x ffmpeg-3.3.2-win64-dev.zip
  - set CPATH=ffmpeg-3.3.2-win64-dev\include;%CPATH%
  - curl -kLO https://ffmpeg.zeranoe.com/builds/win64/dev/ffmpeg-3.3.2-win64-static.zip
  - 7z x ffmpeg-3.3.2-win64-static.zip
  - set LIBRARY_PATH=ffmpeg-3.3.2-win64-static\lib;%LIBRARY_PATH%
  - mingw32-make -j8
artifacts:
  - path: release/KShare.exe
